[font]
normal = { family = "JetBrains Mono" }
size = 12.0


[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 1.3

[cursor.style]
shape = "Block"
blinking = "Never"

[cursor]
vi_mode_style = "None"
blink_interval = 0
blink_timeout = 0
unfocused_hollow = true
thickness = 0.1

[keyboard]
bindings = [
  { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" }
]

[selection]
save_to_clipboard = true


[mouse]
hide_when_typing = true

bindings = [
  { mouse = "Right", mods = "Control", action = "Paste" },
  { mouse = "Middle", mods = "None", action = "Copy" }
]
